services:
  denso-robot-ros2:
    container_name: denso_container
    image: denso-image
    
    build: 
      context: ..
      dockerfile: .docker/Dockerfile
    
    tty: true
    stdin_open: true    
    
    environment:
      - DISPLAY=${DISPLAY} 
      - QT_X11_NO_MITSHM=1 
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ../:/root/denso_ws/src/denso_robot_ros2

    device_cgroup_rules:
      - 'c 81:* rmw'    # câmeras (V4L2, /dev/video*)
      - 'c 189:* rmw'   # USB cru (/dev/bus/usb, ex.: RealSense)
      - 'c 226:* rmw'   # GPU (/dev/dri)

    network_mode: "host"

    command: >
      /bin/bash -c "
      source /opt/ros/humble/setup.bash &&
      if [ ! -d install ]; then
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
      fi &&
      exec bash"